Added file for PowerShell support
rhysd/ghci-color pull request #6
Opened 2022-04-21 05:23 UTC by digitalguy99

I've written a PowerShell(.ps1) equivalent for ghci-color.sh. The program works despite containing some bugs as stated below:

- Prompt occasionally adds an unwanted indentation after a command is executed.
- Error message doesn't show after the execution of an unwanted command.

Suggestions are welcome.

2022-05-23 03:24 UTC, rhysd commented
Is this ready for review?

2022-05-23 07:00 UTC, digitalguy99 commented
@rhysd yes, it is.

2022-05-24 12:13 UTC, rhysd requested changes

2022-05-24 12:13 UTC, rhysd commented on README.md
> +<br>
Can you remove all `&nbsp` and `<br>` since they makes readme less readable.

2022-05-27 12:43 UTC, rhysd approved these changes
Thank you! Looks good.

2022-05-27 12:43 UTC, merged